# Hungarian translation for backintime
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the backintime package.
#
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
# Kósa Lajos <lajos@kosa.co.hu>, 2013.
msgid ""
msgstr ""
"Project-Id-Version: backintime\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2015-03-22 22:25+0100\n"
"PO-Revision-Date: 2015-03-16 23:57+0000\n"
"Last-Translator: Germar <Unknown>\n"
"Language-Team: Hungarian <kde-l10n-hu@kde.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2015-03-22 22:40+0000\n"
"X-Generator: Launchpad (build 17405)\n"
"Language: hu\n"

#: ../../common/configfile.py:248 ../../common/configfile.py:310
#, python-format
msgid "Profile \"%s\" already exists !"
msgstr "A \"%s\" már létezik!"

#: ../../common/configfile.py:279
msgid "You can't remove the last profile !"
msgstr "Nem távolíthatod el az utolsó profilt!"

#: ../../common/config.py:76
msgid "Disabled"
msgstr "Kikapcsolva"

#: ../../common/config.py:77
msgid "At every boot/reboot"
msgstr "Minden (újra)indításkor"

#: ../../common/config.py:78
msgid "Every 5 minutes"
msgstr "Ötpercenként"

#: ../../common/config.py:79
msgid "Every 10 minutes"
msgstr "Tízpercenként"

#: ../../common/config.py:80
msgid "Every 30 minutes"
msgstr "30 percenként"

#: ../../common/config.py:81
msgid "Every hour"
msgstr "Óránként"

#: ../../common/config.py:82
msgid "Every 2 hours"
msgstr "Kétóránként"

#: ../../common/config.py:83
msgid "Every 4 hours"
msgstr "Négyóránként"

#: ../../common/config.py:84
msgid "Every 6 hours"
msgstr "Hatóránként"

#: ../../common/config.py:85
msgid "Every 12 hours"
msgstr "Tizenkétóránként"

#: ../../common/config.py:86
msgid "Custom Hours"
msgstr "Egyedi beállítás (óra)"

#: ../../common/config.py:87
msgid "Every Day"
msgstr "Naponta"

#: ../../common/config.py:88
msgid "Repeatedly (anacron)"
msgstr ""

#: ../../common/config.py:89
msgid "When drive get connected (udev)"
msgstr "Ha csatlakozik a meghajtó (udev)"

#: ../../common/config.py:90
msgid "Every Week"
msgstr "Hetente"

#: ../../common/config.py:91
msgid "Every Month"
msgstr "Havonta"

#: ../../common/config.py:95 ../../common/config.py:102
msgid "Day(s)"
msgstr "Nap"

#: ../../common/config.py:96 ../../common/config.py:103
msgid "Week(s)"
msgstr "Hét"

#: ../../common/config.py:97
msgid "Year(s)"
msgstr "Év"

#: ../../common/config.py:101
msgid "Hour(s)"
msgstr ""

#: ../../common/config.py:104
msgid "Month(s)"
msgstr ""

#: ../../common/config.py:123
msgid " EXPERIMENTAL!"
msgstr " KÍSÉRLETI!"

#: ../../common/config.py:126
msgid "Local"
msgstr "Helyi"

#: ../../common/config.py:127
msgid "SSH"
msgstr "SSH"

#: ../../common/config.py:127 ../../common/config.py:129
#: ../../qt4/settingsdialog.py:1567
msgid "SSH private key"
msgstr "SSH privát kulcs"

#: ../../common/config.py:128
msgid "Local encrypted"
msgstr "Helyi titkosított"

#: ../../common/config.py:128 ../../common/config.py:129
msgid "Encryption"
msgstr "Titkosítás"

#: ../../common/config.py:129
msgid "SSH encrypted"
msgstr "SSH-val titkosított"

#: ../../common/config.py:133
msgid "Default"
msgstr "Alapértelmezett"

#: ../../common/config.py:134
msgid "AES128-CTR"
msgstr "AES128-CTR"

#: ../../common/config.py:135
msgid "AES192-CTR"
msgstr "AES192-CTR"

#: ../../common/config.py:136
msgid "AES256-CTR"
msgstr "AES256-CTR"

#: ../../common/config.py:137
msgid "ARCFOUR256"
msgstr "ARCFOUR256"

#: ../../common/config.py:138
msgid "ARCFOUR128"
msgstr "ARCFOUR128"

#: ../../common/config.py:139
msgid "AES128-CBC"
msgstr "AES128-CBC"

#: ../../common/config.py:140
msgid "3DES-CBC"
msgstr "3DES-CBC"

#: ../../common/config.py:141
msgid "Blowfish-CBC"
msgstr "Blowfish-CBC"

#: ../../common/config.py:142
msgid "Cast128-CBC"
msgstr "Cast128-CBC"

#: ../../common/config.py:143
msgid "AES192-CBC"
msgstr "AES192-CBC"

#: ../../common/config.py:144
msgid "AES256-CBC"
msgstr "AES256-CBC"

#: ../../common/config.py:145
msgid "ARCFOUR"
msgstr "ARCFOUR"

#: ../../common/config.py:151
msgid "Main profile"
msgstr "Fő profil"

#: ../../common/config.py:286 ../../common/config.py:293
#: ../../common/config.py:304 ../../common/config.py:309
#, python-format
msgid "Profile: \"%s\""
msgstr "Profil: \"%s\""

#: ../../common/config.py:286
msgid "Snapshots folder is not valid !"
msgstr "A pillanatkép-könyvtár nem érvényes"

#: ../../common/config.py:293
msgid "You must select at least one folder to backup !"
msgstr "Legalább egy könyvtárat ki kell jelölnie a mentéshez"

#: ../../common/config.py:304
msgid "You can't include backup folder !"
msgstr "Nem adható hozzá a biztonsági mentés mappája"

#: ../../common/config.py:309
msgid "You can't include a backup sub-folder !"
msgstr "Nem adható hozzá a biztonsági mentés almappája"

#: ../../common/config.py:368
#, python-format
msgid "%s is not a folder !"
msgstr "A(z) %s nem könyvtár"

#: ../../common/config.py:381 ../../common/config.py:394
#, python-format
msgid ""
"Can't write to: %s\n"
"Are you sure you have write access ?"
msgstr ""
"Nem tudok ide írni: %s\n"
"Biztos, hogy van írási jogod?"

#: ../../common/config.py:1383
msgid ""
"Can't find crontab.\n"
"Are you sure cron is installed ?\n"
"If not you should disable all automatic backups."
msgstr ""
"A crontab nem található.\n"
"Biztos, hogy telepítve van a cron?\n"
"Ha nem, akkor ki kell kapcsolni az automatikus biztonsági mentést."

#: ../../common/config.py:1422
#, python-format
msgid ""
"Could not install Udev rule for profile %(profile_id)s. DBus Service "
"'%(dbus_interface)s' wasn't available"
msgstr ""

#: ../../common/config.py:1433
#, python-format
msgid "Schedule udev doesn't work with mode %s"
msgstr "Az udev időzítése nem működik ezzel a móddal: %s"

#: ../../common/config.py:1441
#, python-format
msgid "Couldn't find UUID for \"%s\""
msgstr "Nem találom a \"%s\" meghajtó UUID-ját"

#: ../../common/encfstools.py:99
#, python-format
msgid ""
"Can't mount '%(command)s':\n"
"\n"
"%(error)s"
msgstr ""
"Nem tudtam felcsatolni a következőt: '%(command)s':\n"
"\n"
"%(error)s"

#: ../../common/encfstools.py:109
#, python-format
msgid "Can't unmount encfs %s"
msgstr "Nem tudom lecsatolni a(z) %s encfs-t"

#: ../../common/encfstools.py:153
msgid "Config for encrypted folder not found."
msgstr "A titkosított mappa konfigurációja nem található"

#: ../../common/encfstools.py:157
msgid ""
"\n"
"Create a new encrypted folder?"
msgstr ""
"\n"
"Létrehozzak egy új titkosított mappát?"

#: ../../common/encfstools.py:158
msgid "Cancel"
msgstr "Mégsem"

#: ../../common/encfstools.py:161
msgid "Please confirm password"
msgstr "Erősítsd meg a jelszót"

#: ../../common/encfstools.py:165
msgid "Password doesn't match"
msgstr "A jelszavakat nem egyeznek"

#: ../../common/encfstools.py:170
msgid "encfs not found. Please install e.g. 'apt-get install encfs'"
msgstr "Nem találom az encfs-t. Telepítsd pl. így: 'apt-get install encfs'"

#: ../../common/encfstools.py:179 ../../common/sshtools.py:226
#, python-format
msgid ""
"%(user)s is not member of group 'fuse'.\n"
" Run 'sudo adduser %(user)s fuse'. To apply changes logout and login again.\n"
"Look at 'man backintime' for further instructions."
msgstr ""
"A(z) %(user)s nem tagja a 'fuse' csoportnak.\n"
" Futtasd le a 'sudo adduser %(user)s fuse' parancsot, majd jelentkezz ki és "
"vissza.\n"
"Nézd meg a 'man backintime'-ot további részletekért."

#: ../../common/encfstools.py:192
msgid ""
"encfs version 1.7.2 and before has a bug with option --reverse. Please "
"update encfs"
msgstr ""
"Az encfs az 1.7.2-es és korábbi verzióknál hibás, ha a --reverse opciót "
"használod. Frissítsd az encfs-t"

#: ../../common/encfstools.py:474 ../../common/encfstools.py:506
#: ../../common/snapshots.py:991 ../../common/snapshots.py:1225
#: ../../qt4/app.py:77
msgid "Take snapshot"
msgstr "Pillanatkép készítése"

#: ../../common/mount.py:197
#, python-format
msgid ""
"Hash collision occurred in hash_id %s. Incrementing global value "
"hash_collision and try again."
msgstr ""
"Hash-ütközés történt: hash_id %s. Megnövelem a hash_collision értékét, és "
"újra próbálom."

#: ../../common/mount.py:248
#, python-format
msgid "mountpoint %s not empty."
msgstr "A %s csatolási pont foglalt"

#: ../../common/mount.py:285
msgid "Mountprocess lock timeout"
msgstr "A csatolási folyamat túl sok időt vett igénybe"

#: ../../common/password.py:422
#, python-format
msgid "Profile '%(profile)s': Enter password for %(mode)s: "
msgstr ""
"A(z) '%(profile)s' profil: add meg a jelszót a következőhöz: %(mode)s "

#: ../../common/snapshots.py:172 ../../qt4/app.py:201 ../../qt4/app.py:1187
msgid "Now"
msgstr "Most"

#: ../../common/snapshots.py:183
msgid "WITH ERRORS !"
msgstr "HIBÁKKAL!"

#: ../../common/snapshots.py:309
msgid ""
"### This log has been decoded with automatic search pattern\n"
"### If some paths are not decoded you can manually decode them with:\n"
msgstr ""
"### Ezt a naplófájlt automatikus keresési mintával dekódolták\n"
"### Ha néhány útvonal dekódolása elmaradt, a következővel tudod kézzel "
"dekódolni:\n"

#: ../../common/snapshots.py:483
msgid "FAILED"
msgstr "MEGHIÚSULT"

#: ../../common/snapshots.py:597
msgid "Restore permissions:"
msgstr "Engedélyek visszaállítása:"

#: ../../common/snapshots.py:735
msgid ""
"Back In Time changed its backup format.\n"
"\n"
"Your old snapshots can be moved according to this new format. OK?"
msgstr ""
"A Back in Time  megváltoztatta a mentési formátumát.\n"
"\n"
"A régi pillanatképeket át tudjuk konvertálni ebbe az új formátumba. Rendben?"

#: ../../common/snapshots.py:743
#, python-format
msgid ""
"%s profiles found. \n"
"\n"
"The new backup format supports storage of different users and profiles on "
"the same location. Do you want the same location for both profiles? \n"
"\n"
"(The program will still be able to discriminate between them)"
msgstr ""
"A(z) %s profilokat nem találom.\n"
"\n"
"Az új mentési formátum lehetővé teszi különböző felhasználók és profilok "
"tárolását ugyanazon a helyen. Szeretnéd mindkét profilt ugyanazon a helyen "
"tárolni?\n"
"\n"
"(A program ettől még meg fogja tudni különböztetni őket)"

#: ../../common/snapshots.py:746
msgid ""
"No profiles are found. Will have to update to profiles first, please restart "
"Back In Time"
msgstr ""
"Nem találtam profilt. Először frissíteni kell a profilokat, először indítsd "
"újra a Back In Time-ot"

#: ../../common/snapshots.py:786
#, python-format
msgid ""
"%(snapshots_left)s\n"
"of profile %(profile_id)s are not moved to their new location\n"
"Do you want to proceed?\n"
"(Back In Time will be able to continue taking snapshots, however the "
"remaining snapshots will not be considered for automatic removal)\n"
"\n"
"If not Back In Time will restore former settings for this profile, however "
"cannot continue taking snapshots"
msgstr ""
"A(z) %(profile_id)s profil\n"
"%(snapshots_left)s tartalma nem került át az új helyére.\n"
"Folytassam?\n"
"(A Back In Time továbbra is tud pillanatképeket készíteni, de a megmaradt "
"pillanatképeket az automatikus eltávolítás figyelmen kívül fogja hagyni)\n"
"Ha nem folytatom, a Back In Time visszaállítja ennek a profilnak a korábbi "
"beállításait, de nem fog tudni pillanatképeket készíteni"

#: ../../common/snapshots.py:794
#, python-format
msgid ""
"Former settings of profile %s are restored.\n"
"Back In Time cannot continue taking new snapshots.\n"
"\n"
"You can manually move the snapshots, \n"
"if you are done restart Back In Time to proceed"
msgstr ""
"A %s profil korábbi beállításai visszaállítva.\n"
"A Back in Time nem tud újabb pillanatképeket készíteni.\n"
"\n"
"Kézzel tudod mozgatni a pillanatképeket,\n"
"ha befejezted, a folytatáshoz indítsd újra a Back in Time-ot"

#: ../../common/snapshots.py:804
msgid ""
"Update was successful!\n"
"\n"
"Back In Time will continue taking snapshots again as scheduled"
msgstr ""
"A frissítés sikeres volt.\n"
"\n"
"A Back in Time folytatja a pillanatképek készítését az időzítés szerint."

#: ../../common/snapshots.py:809
msgid ""
"Are you sure you do not want to move your old snapshots?\n"
"\n"
"\n"
"If you do, you will not see these questions again next time, Back In Time "
"will continue making snapshots again, but smart-remove cannot take your old "
"snapshots into account any longer!\n"
"\n"
"If you do not, you will be asked again next time you start Back In Time."
msgstr ""
"Biztos, hogy nem akarod áthelyezni a pillanatképeket?\n"
"\n"
"\n"
"Ha mégis,ezt a kérdést nem kapod meg újra, és a Back In Time újra készít "
"majd pillanatképeket, de az okos eltávolítás nem veszi majd figyelembe a "
"régi pillanatképeidet!\n"
"\n"
"Ha nem, a Back In Time következő indításakor újra megkapod ezt a kérdést."

#: ../../common/snapshots.py:817
msgid "Back In Time will continue taking snapshots again as scheduled"
msgstr "A Back in Time újra készít majd pillanatképeket az időzítés szerint."

#: ../../common/snapshots.py:819
msgid ""
"Back In Time still cannot continue taking new snapshots.\n"
"Restart Back In Time to see the questions again"
msgstr ""
"A Back in Time nem tud újabb pillanatképeket készíteni.\n"
"Indítsd újra a Back in Time -ot, hogy ismét láthasd a kérdéseket."

#: ../../common/snapshots.py:836
msgid "Deferring backup while on battery"
msgstr ""

#: ../../common/snapshots.py:895
msgid ""
"Can't find snapshots folder.\n"
"If it is on a removable drive please plug it."
msgstr ""
"A pillanatképek könyvtára nem található.\n"
"Ha egy eltávolítható adathordozón van, csatlakoztasd."

#: ../../common/snapshots.py:897
#, python-format
msgid "Waiting %s second."
msgid_plural "Waiting %s seconds."
msgstr[0] "%s másodperc várakozás."
msgstr[1] "%s másodperc várakozás."

#: ../../common/snapshots.py:923
#, python-format
msgid "Failed to take snapshot %s !!!"
msgstr "A %s pillanatkép készítése meghiúsult!!!"

#: ../../common/snapshots.py:932
msgid "Finalizing"
msgstr "Véglegesítés"

#: ../../common/snapshots.py:1061
#, python-format
msgid "Can't create folder: %s"
msgstr "A(z) %s mappa nem hozható létre"

#: ../../common/snapshots.py:1077
msgid "..."
msgstr "..."

#: ../../common/snapshots.py:1102
#, python-format
msgid "Can't remove folder: %s"
msgstr "A(z) %s mappa nem távolítható el"

#: ../../common/snapshots.py:1179
#, python-format
msgid "Compare with snapshot %s"
msgstr "Összehasonlítás a következő pillanatképpel: %s"

#: ../../common/snapshots.py:1198
msgid "Create hard-links"
msgstr "Hard-linkek készítése"

#: ../../common/snapshots.py:1271
msgid "Save config file ..."
msgstr "Konfigurációs fájl mentése..."

#: ../../common/snapshots.py:1277
msgid "Save permission ..."
msgstr "Hozzáférési jogosultságok mentése..."

#: ../../common/snapshots.py:1302
msgid "Save permission over ssh failed. Retry normal method"
msgstr ""

#: ../../common/snapshots.py:1347
#, python-format
msgid "Can't rename %(new_path)s to %(path)s"
msgstr "Nem tudom a(z) %(path)s útvonalat átnevezni erre: %(new_path)s"

#: ../../common/snapshots.py:1465 ../../common/snapshots.py:1497
#: ../../qt4/settingsdialog.py:554
msgid "Smart remove"
msgstr "Okos eltávolítás"

#: ../../common/snapshots.py:1472
msgid "Remove old snapshots"
msgstr "Régi pillanatképek eltávolítása"

#: ../../common/snapshots.py:1502
msgid "Try to keep min free space"
msgstr "A minimálisan megadott szabad hely kialakítása"

#: ../../common/snapshots.py:1538
#, python-format
msgid "Try to keep min %d%% free inodes"
msgstr "Megpróbálok legalább %d%% szabad inode-ot tartani"

#: ../../common/sshtools.py:117
#, python-format
msgid "Can't mount %s"
msgstr "Nem tudom felcsatolni: %s"

#: ../../common/sshtools.py:124
#, python-format
msgid "Can't unmount sshfs %s"
msgstr "Nem tudom felcsatolni a(z) %s sshfs-t"

#: ../../common/sshtools.py:202
#, python-format
msgid ""
"Failed to unlock SSH private key:\n"
"Error: %s"
msgstr ""
"Nem tudtam feloldani az SSH privát kulcsát:\n"
"Hiba: %s"

#: ../../common/sshtools.py:212
msgid ""
"Could not unlock ssh private key. Wrong password or password not available "
"for cron."
msgstr ""
"Nem tudtam feloldani az ssh privát kulcsát. Hibás jelszó vagy a cron nem éri "
"el a jelszót."

#: ../../common/sshtools.py:217
msgid "sshfs not found. Please install e.g. 'apt-get install sshfs'"
msgstr ""
"Nem találom az sshfs-t. Telepítsd pl. az 'apt-get install sshfs' paranccsal."

#: ../../common/sshtools.py:236
#, python-format
msgid ""
"Password-less authentication for %(user)s@%(host)s failed. Look at 'man "
"backintime' for further instructions."
msgstr ""
"A %(user)s@%(host)s nem tudott jelszó nélkül bejelentkeztni. Nézd meg a 'man "
"backintime'-ot további részletekért."

#: ../../common/sshtools.py:251
#, python-format
msgid ""
"Cipher %(cipher)s failed for %(host)s:\n"
"%(err)s"
msgstr ""
"A(z) %(cipher)s nem sikerült a %(host)s esetében:\n"
"%(err)s"

#: ../../common/sshtools.py:278
#, python-format
msgid "%s not found in ssh_known_hosts."
msgstr "A(z) %s nem található itt: ssh_known_hosts."

#: ../../common/sshtools.py:298
#, python-format
msgid ""
"Remote path exists but is not a directory:\n"
" %s"
msgstr ""
"A távoli útvonal létezik, de nem könyvtár:\n"
" %s"

#: ../../common/sshtools.py:300
#, python-format
msgid ""
"Remote path is not writeable:\n"
" %s"
msgstr ""
"A távoli útvonal nem írható:\n"
" %s"

#: ../../common/sshtools.py:302
#, python-format
msgid ""
"Remote path is not executable:\n"
" %s"
msgstr ""
"A távoli útvonal nem futtatható:\n"
" %s"

#: ../../common/sshtools.py:304
#, python-format
msgid ""
"Couldn't create remote path:\n"
" %s"
msgstr ""
"Nem tudom távoli útvonalat elkészíteni:\n"
" %s"

#: ../../common/sshtools.py:323
#, python-format
msgid "Ping %s failed. Host is down or wrong address."
msgstr ""
"A(z) %s ping sikertelen volt. A kiszolgáló nem működik vagy rossz a cím."

#: ../../common/sshtools.py:346 ../../common/sshtools.py:408
#, python-format
msgid ""
"Remote host %(host)s doesn't support '%(command)s':\n"
"%(err)s\n"
"Look at 'man backintime' for further instructions"
msgstr ""
"A(z) %(host)s távoli kiszolgáló nem támogatja a következőt: '%(command)s':\n"
"%(err)s\n"
"Nézd meg a 'man backintime'-ot további részletekért"

#: ../../common/sshtools.py:412
#, python-format
msgid ""
"Check commands on host %(host)s returned unknown error:\n"
"%(err)s\n"
"Look at 'man backintime' for further instructions"
msgstr ""
"A parancsok ellenőzése a(z) %(host)s kiszolgálón ismeretlen hibát okozott:\n"
"%(err)s\n"
"Nézd meg a 'man backintime'-ot további részletekért"

#: ../../common/sshtools.py:425
#, python-format
msgid "Remote host %s doesn't support hardlinks"
msgstr "A(z) %s kiszolgáló nem támogatja a hardlinkeket."

#: ../../qt4/app.py:80
msgid "Refresh snapshots list"
msgstr "Pillanatképek listájának frissítése"

#: ../../qt4/app.py:83 ../../qt4/app.py:931
msgid "Snapshot Name"
msgstr "Pillanatkép neve"

#: ../../qt4/app.py:86
msgid "Remove Snapshot"
msgstr "Pillanatkép eltávolítása"

#: ../../qt4/app.py:89
msgid "View Snapshot Log"
msgstr "A pillanatképek naplófájljának megtekintése"

#: ../../qt4/app.py:92
msgid "View Last Log"
msgstr "Utolsó naplófájl megtekintése"

#: ../../qt4/app.py:97 ../../qt4/settingsdialog.py:50
msgid "Settings"
msgstr "Beállítások"

#: ../../qt4/app.py:102
msgid "Shutdown"
msgstr "Leállítás"

#: ../../qt4/app.py:103
msgid "Shutdown system after snapshot has finished."
msgstr "Állítsd le a rendszert, ha elkészült a pillanatkép."

#: ../../qt4/app.py:109
msgid "Exit"
msgstr "Kilépés"

#: ../../qt4/app.py:118 ../../qt4/app.py:135 ../../qt4/app.py:241
msgid "Help"
msgstr "Súgó"

#: ../../qt4/app.py:121
msgid "Website"
msgstr "Honlap"

#: ../../qt4/app.py:123
msgid "Changelog"
msgstr ""

#: ../../qt4/app.py:125
msgid "FAQ"
msgstr "GYIK"

#: ../../qt4/app.py:127
msgid "Ask a question"
msgstr "Kérdezz"

#: ../../qt4/app.py:129
msgid "Report a bug"
msgstr "Hiba jelentése"

#: ../../qt4/app.py:132 ../../qt4/app.py:1292
msgid "About"
msgstr "Névjegy"

#: ../../qt4/app.py:147 ../../qt4/app.py:204 ../../qt4/snapshotsdialog.py:95
msgid "Snapshots"
msgstr "Pillanatképek"

#: ../../qt4/app.py:162
msgid "Up"
msgstr "Fel"

#: ../../qt4/app.py:173 ../../qt4/settingsdialog.py:1755
msgid "Show hidden files"
msgstr "Rejtett fájlok megjelenítése"

#: ../../qt4/app.py:182 ../../qt4/app.py:197 ../../qt4/app.py:231
#: ../../qt4/restoredialog.py:62 ../../qt4/settingsdialog.py:1799
#: ../../qt4/snapshotsdialog.py:133 ../../qt4/snapshotsdialog.py:138
msgid "Restore"
msgstr "Visszaállítás"

#: ../../qt4/app.py:184 ../../qt4/restoredialog.py:35
#: ../../qt4/snapshotsdialog.py:135
msgid "Restore to ..."
msgstr "Visszaállítás ide..."

#: ../../qt4/app.py:192
msgid "Restore and delete new files"
msgstr ""

#: ../../qt4/app.py:199
#, python-format
msgid ""
"Restore selected file or folder.\n"
"If this button is grayed out this is most likely because \"%(now)s\" is "
"selected in left hand snapshots list."
msgstr ""

#: ../../qt4/app.py:211
msgid "Snapshot"
msgstr ""

#: ../../qt4/app.py:222
msgid "View"
msgstr ""

#: ../../qt4/app.py:262
msgid "Shortcuts"
msgstr "Billentyűparancsok"

#: ../../qt4/app.py:280
msgid ""
"This folder doesn't exist\n"
"in the current snapshot !"
msgstr ""
"A jelenlegi pillanatképben\n"
"nincs benne ez a mappa!"

#: ../../qt4/app.py:357 ../../qt4/app.py:649 ../../qt4/app.py:666
#: ../../qt4/qt4systrayicon.py:60
msgid "Done"
msgstr "Kész"

#: ../../qt4/app.py:395
#, python-format
msgid ""
"%(appName)s is not configured. Would you like to restore a previous "
"configuration?"
msgstr ""

#: ../../qt4/app.py:419
msgid ""
"Can't find snapshots folder.\n"
"If it is on a removable drive please plug it and then press OK"
msgstr ""
"Nem található a pillanatképek könyvtára.\n"
"Ha egy eltávolítható lemezen van, csatlakoztasd és nyomd meg az OK-t"

#: ../../qt4/app.py:451
msgid ""
"If you close this window Back In Time will not be able to shutdown your "
"system when the snapshot has finished.\n"
"Do you really want to close?"
msgstr ""
"Ha bezárod ezt az ablakot, a Back In Time nem tudja lekapcsolni a rendszert "
"a biztonsági mentés elvégzése után.\n"
"Biztos bezárod?"

#: ../../qt4/app.py:641 ../../qt4/app.py:677
msgid "Working:"
msgstr "Dolgozik:"

#: ../../qt4/app.py:669
msgid "Done, no backup needed"
msgstr "Kész, nincs szükség biztonsági mentés készítésére"

#: ../../qt4/app.py:681
msgid "Error:"
msgstr "Hiba:"

#: ../../qt4/app.py:700 ../../qt4/qt4systrayicon.py:148
msgid "Sent:"
msgstr ""

#: ../../qt4/app.py:701 ../../qt4/qt4systrayicon.py:149
msgid "Speed:"
msgstr ""

#: ../../qt4/app.py:702 ../../qt4/qt4systrayicon.py:150
msgid "ETA:"
msgstr ""

#: ../../qt4/app.py:750
msgid "Global"
msgstr "Globális"

#: ../../qt4/app.py:751
msgid "Root"
msgstr "Root"

#: ../../qt4/app.py:752
msgid "Home"
msgstr "Home"

#: ../../qt4/app.py:767
msgid "Backup folders"
msgstr "Biztonsági mentés mappái"

#: ../../qt4/app.py:847
msgid "This is NOT a snapshot but a live view of your local files"
msgstr ""

#: ../../qt4/app.py:857
msgid "Today"
msgstr "Ma"

#: ../../qt4/app.py:861
msgid "Yesterday"
msgstr "Tegnap"

#: ../../qt4/app.py:865
msgid "This week"
msgstr "Ezen a héten"

#: ../../qt4/app.py:869
msgid "Last week"
msgstr "Múlt héten"

#: ../../qt4/app.py:901
#, python-format
msgid "Last check %s"
msgstr ""

#: ../../qt4/app.py:965
#, python-format
msgid ""
"Are you sure you want to remove the snapshot:\n"
"%s"
msgstr ""
"Biztos, hogy el akar távolítani a következő pillanatképet:\n"
"%s?"

#: ../../qt4/app.py:1027
msgid ""
"Are you sure you want to remove all newer files in your original folder?"
msgstr ""

#: ../../qt4/app.py:1031
msgid ""
"WARNING: deleting files in filesystem root could break your whole system!!!"
msgstr ""

#: ../../qt4/app.py:1034
#, python-format
msgid ""
"Actually files will be backed up with trailing '%(suffix)s' instead of being "
"removed. You can turn this off in\n"
"Settings > Options > %(backup_option)s"
msgstr ""

#: ../../qt4/app.py:1039 ../../qt4/settingsdialog.py:626
msgid "Backup replaced files on restore"
msgstr ""

#: ../../qt4/app.py:1042
msgid "Files to be restored:"
msgstr ""

#: ../../qt4/app.py:1049
msgid "Do you really want to restore this files(s):"
msgstr ""

#: ../../qt4/app.py:1183
#, python-format
msgid "Snapshot: %s"
msgstr "Pillanatkép: %s"

#: ../../qt4/app.py:1184
#, python-format
msgid "View the snapshot made at %s"
msgstr "A %s időpontban észült pillanatkép megtekintése"

#: ../../qt4/app.py:1186
msgid "View the current disk content"
msgstr "A lemez jelenlegi tartalmának megtekintése"

#: ../../qt4/app.py:1225
#, python-format
msgid "Restore '%s'"
msgstr "A(z) '%s' visszaállítása"

#: ../../qt4/app.py:1226
#, python-format
msgid "Restore '%s' to ..."
msgstr "A(z) '%s' visszaállítása ide..."

#: ../../qt4/app.py:1227
#, python-format
msgid "Restore '%s' and delete new files"
msgstr ""

#: ../../qt4/app.py:1312 ../../qt4/app.py:1329
msgid "Authors"
msgstr ""

#: ../../qt4/app.py:1313 ../../qt4/app.py:1332
msgid "Translations"
msgstr ""

#: ../../qt4/app.py:1314 ../../qt4/app.py:1335
msgid "License"
msgstr ""

#: ../../qt4/logviewdialog.py:44
msgid "Error Log View"
msgstr "Hibanapló megtekintése"

#: ../../qt4/logviewdialog.py:52 ../../qt4/settingsdialog.py:58
#: ../../qt4/settingsdialog.py:286 ../../qt4/settingsdialog.py:1880
msgid "Profile:"
msgstr "Profil:"

#: ../../qt4/logviewdialog.py:64
msgid "Filter:"
msgstr "Szűrő:"

#: ../../qt4/logviewdialog.py:70 ../../qt4/settingsdialog.py:668
msgid "All"
msgstr "Mindegyik"

#: ../../qt4/logviewdialog.py:71 ../../qt4/settingsdialog.py:666
msgid "Errors"
msgstr "Hibák"

#: ../../qt4/logviewdialog.py:76
msgid "Changes"
msgstr "Változások"

#: ../../qt4/logviewdialog.py:79
msgid "Informations"
msgstr "Információk"

#: ../../qt4/logviewdialog.py:88
msgid "[E] Error, [I] Information, [C] Change"
msgstr "[E] hiba, [I] információ, [C] változtat"

#: ../../qt4/logviewdialog.py:91
msgid "decode paths"
msgstr "dekódolás útvonalai"

#: ../../qt4/messagebox.py:57
msgid "Error"
msgstr ""

#: ../../qt4/messagebox.py:63
msgid "Question"
msgstr ""

#: ../../qt4/qt4systrayicon.py:64
msgid "Start BackInTime"
msgstr ""

#: ../../qt4/qt4systrayicon.py:119
msgid "Working..."
msgstr "Dolgozom..."

#: ../../qt4/restoredialog.py:75
msgid "Show full Log"
msgstr ""

#: ../../qt4/settingsdialog.py:67
msgid "Edit"
msgstr "Szerkesztés"

#: ../../qt4/settingsdialog.py:71 ../../qt4/settingsdialog.py:463
msgid "Add"
msgstr ""

#: ../../qt4/settingsdialog.py:75 ../../qt4/settingsdialog.py:420
#: ../../qt4/settingsdialog.py:479
msgid "Remove"
msgstr ""

#: ../../qt4/settingsdialog.py:90
msgid "General"
msgstr "Általános"

#: ../../qt4/settingsdialog.py:100 ../../qt4/settingsdialog.py:1882
msgid "Mode:"
msgstr "Mód:"

#: ../../qt4/settingsdialog.py:115 ../../qt4/settingsdialog.py:1552
msgid "Where to save snapshots"
msgstr "Hova mentse a pillanatképeket"

#: ../../qt4/settingsdialog.py:131
msgid "Folder"
msgstr ""

#: ../../qt4/settingsdialog.py:139
msgid "SSH Settings"
msgstr "Az SSH beállításai"

#: ../../qt4/settingsdialog.py:151 ../../qt4/settingsdialog.py:274
msgid "Host:"
msgstr "Kiszolgáló:"

#: ../../qt4/settingsdialog.py:156
msgid "Port:"
msgstr "Port:"

#: ../../qt4/settingsdialog.py:161 ../../qt4/settingsdialog.py:280
msgid "User:"
msgstr "Felhasználó:"

#: ../../qt4/settingsdialog.py:166
msgid "Path:"
msgstr "Elérési út:"

#: ../../qt4/settingsdialog.py:172
msgid "Cipher:"
msgstr "Cipher:"

#: ../../qt4/settingsdialog.py:178
msgid "Private Key:"
msgstr "Privát kulcs"

#: ../../qt4/settingsdialog.py:187
msgid "Key File"
msgstr ""

#: ../../qt4/settingsdialog.py:226 ../../qt4/settingsdialog.py:235
#: ../../qt4/settingsdialog.py:241
msgid "Password"
msgstr "Jelszó"

#: ../../qt4/settingsdialog.py:247
msgid "Save Password to Keyring"
msgstr "Jelszó mentése a kulcstartóba"

#: ../../qt4/settingsdialog.py:250
msgid "Cache Password for Cron (Security issue: root can read password)"
msgstr ""
"Jelszó mentése a Cron számára (biztonsági figyelmeztetés: a root látja a "
"jelszót)"

#: ../../qt4/settingsdialog.py:262
msgid "Advanced"
msgstr "Szakértői"

#: ../../qt4/settingsdialog.py:292 ../../qt4/settingsdialog.py:1619
msgid "Full snapshot path: "
msgstr ""

#: ../../qt4/settingsdialog.py:299
msgid "Schedule"
msgstr "Ütemterv"

#: ../../qt4/settingsdialog.py:309
msgid "Day:"
msgstr "Nap:"

#: ../../qt4/settingsdialog.py:320
msgid "Weekday:"
msgstr "Hét napja:"

#: ../../qt4/settingsdialog.py:331
msgid "Hour:"
msgstr "Óra:"

#: ../../qt4/settingsdialog.py:342
msgid "Hours:"
msgstr "Óra:"

#: ../../qt4/settingsdialog.py:351
msgid ""
"Run Back In Time repeatedly. This is useful if the computer is not running "
"regular."
msgstr ""

#: ../../qt4/settingsdialog.py:356
msgid "Every:"
msgstr ""

#: ../../qt4/settingsdialog.py:374
msgid ""
"Run Back In Time as soon as the drive is connected (only once every X "
"days).\n"
"You will be prompted for your sudo password."
msgstr ""
"Futtassa a Back In Time-ot, amint csatolod a meghajtót (X naponta egyszer).\n"
"Be fogja kérni a sudo jelszót."

#: ../../qt4/settingsdialog.py:387
msgid "Include"
msgstr "Hozzáadás"

#: ../../qt4/settingsdialog.py:393
msgid "Include files and folders"
msgstr "Felveendő fájlok és mappák"

#: ../../qt4/settingsdialog.py:412 ../../qt4/settingsdialog.py:467
msgid "Add file"
msgstr "Fájl hozzáadása"

#: ../../qt4/settingsdialog.py:416 ../../qt4/settingsdialog.py:471
msgid "Add folder"
msgstr "Mappa hozzáadása"

#: ../../qt4/settingsdialog.py:426
msgid "Exclude"
msgstr "Kihagyás"

#: ../../qt4/settingsdialog.py:429
msgid ""
"<b>Warning:</b> Wildcards ('foo*', '[fF]oo', 'fo?') will be ignored with "
"mode 'SSH encrypted'.\n"
"Only separate asterisk are allowed ('foo/*', 'foo/**/bar')"
msgstr ""
"<b>Figyelem:</b> a helyettesítő karaktreket ('foo*', '[fF]oo', 'fo?') az "
"'SSH encrypted' mód nem veszi figyelembe.\n"
"Csak az elválasztó csillag megengedett ('foo/*', 'foo/**/bar')"

#: ../../qt4/settingsdialog.py:437
msgid "Exclude patterns, files or folders"
msgstr "Kihagyandó minták, fájlok és mappák"

#: ../../qt4/settingsdialog.py:453
msgid "Highly recommended:"
msgstr "Erősen ajánlott:"

#: ../../qt4/settingsdialog.py:475
msgid "Add default"
msgstr ""

#: ../../qt4/settingsdialog.py:486
msgid "Exclude files bigger than: "
msgstr ""

#: ../../qt4/settingsdialog.py:487
msgid ""
"Exclude files bigger than value in Mb.\n"
"With 'Full rsync mode' disabled this will only affect new files\n"
"because for rsync this is a transfer option, not an exclude option.\n"
"So big files that has been backed up before will remain in snapshots\n"
"even if they had changed."
msgstr ""

#: ../../qt4/settingsdialog.py:505
msgid "Auto-remove"
msgstr "Automatikus eltávolítás"

#: ../../qt4/settingsdialog.py:512
msgid "Older than:"
msgstr "Régebbi, mint:"

#: ../../qt4/settingsdialog.py:527
msgid "If free space is less than:"
msgstr "Ha a szabad hely kevesebb, mint:"

#: ../../qt4/settingsdialog.py:540
msgid "If free inodes is less than:"
msgstr "Ha a szabad inode-ok száma kevesebb, mint"

#: ../../qt4/settingsdialog.py:563
msgid "Keep all snapshots for the last"
msgstr "Tartsd meg a pillanatképeket a legutóbbi:"

#: ../../qt4/settingsdialog.py:567 ../../qt4/settingsdialog.py:573
msgid "day(s)"
msgstr "napból"

#: ../../qt4/settingsdialog.py:569
msgid "Keep one snapshot per day for the last"
msgstr "Tarts meg napi egy pillanatképet a legutóbbi:"

#: ../../qt4/settingsdialog.py:575
msgid "Keep one snapshot per week for the last"
msgstr "Tarts meg heti egy pillanatképet a legutóbbi:"

#: ../../qt4/settingsdialog.py:579
msgid "weeks(s)"
msgstr "hétből"

#: ../../qt4/settingsdialog.py:581
msgid "Keep one snapshot per month for the last"
msgstr "Tarts meg havi egy pillanatképet a legutóbbi:"

#: ../../qt4/settingsdialog.py:585
msgid "month(s)"
msgstr "hónapból"

#: ../../qt4/settingsdialog.py:587
msgid "Keep one snapshot per year for all years"
msgstr "Tarts meg évi egy pillanatképet a legutóbbi:"

#: ../../qt4/settingsdialog.py:594
msgid "Don't remove named snapshots"
msgstr "Ne távolítsa el a névvel ellátott pillanatképeket"

#: ../../qt4/settingsdialog.py:606
msgid "Options"
msgstr "Beállítások"

#: ../../qt4/settingsdialog.py:611
msgid "Enable notifications"
msgstr "Értesítések engedélyezése"

#: ../../qt4/settingsdialog.py:614
msgid "Disable snapshots when on battery"
msgstr "Pillanatképek készítésének tiltása akkumulátorról működésnél"

#: ../../qt4/settingsdialog.py:617
msgid "Power status not available from system"
msgstr "A rendszer nem adja meg az energiaellátás állapotát"

#: ../../qt4/settingsdialog.py:620
msgid "Run only one snapshot at a time"
msgstr ""

#: ../../qt4/settingsdialog.py:621
msgid ""
"Other snapshots will be blocked until the current snapshot is done.\n"
"This is a global option. So it will effect all profiles for this user.\n"
"But you need to activate this for all other users, too."
msgstr ""

#: ../../qt4/settingsdialog.py:627
#, python-format
msgid ""
"Newer versions of files will be renamed with trailing '%(suffix)s' before "
"restoring.\n"
"If you don't need them anymore you can remove them with '%(cmd)s'"
msgstr ""

#: ../../qt4/settingsdialog.py:636
msgid "Continue on errors (keep incomplete snapshots)"
msgstr "Folytatás hibák esetén (megtartja a nem teljes pillanatképeket)"

#: ../../qt4/settingsdialog.py:639
msgid "Use checksum to detect changes"
msgstr "Checksum használata hibák felfedezéséhez"

#: ../../qt4/settingsdialog.py:642
msgid "Full rsync mode. May be faster but:"
msgstr "Teljes rsync-mód. Lassabb lehet, de:"

#: ../../qt4/settingsdialog.py:643
msgid ""
"- snapshots are not read-only\n"
"- destination file-system must support all linux attributes (dates, rights, "
"user, group ...)"
msgstr ""
"- a pillanatképek nem csak olvashatók\n"
"- a célfájlrendszernek támogatnia kell minden linux-attribútumot (dátumok, "
"jogok, felhasználó, csoport...)"

#: ../../qt4/settingsdialog.py:650
msgid "Take a new snapshot reagardless of there were changes or not."
msgstr ""

#: ../../qt4/settingsdialog.py:653
msgid "Check for changes (don't take a new snapshot if nothing changed)"
msgstr ""
"Változások ellenőrzése (nem készít új pillanatképet, ha nincs változás)"

#: ../../qt4/settingsdialog.py:660
msgid "Log Level:"
msgstr "Naplózás szintje:"

#: ../../qt4/settingsdialog.py:665
msgid "None"
msgstr "Egyik sem"

#: ../../qt4/settingsdialog.py:667
msgid "Changes & Errors"
msgstr "Változások & Hibák"

#: ../../qt4/settingsdialog.py:678
msgid "Expert Options"
msgstr "Szakértői beállítások"

#: ../../qt4/settingsdialog.py:683
msgid "Change these options only if you really know what you are doing !"
msgstr ""
"Ezeket a beállításokat csak akkor változtasd meg, ha biztosan tudod, mit "
"csinálsz!"

#: ../../qt4/settingsdialog.py:687
msgid "Run 'nice':"
msgstr ""

#: ../../qt4/settingsdialog.py:693 ../../qt4/settingsdialog.py:705
msgid "as cron job"
msgstr ""

#: ../../qt4/settingsdialog.py:696 ../../qt4/settingsdialog.py:711
#: ../../qt4/settingsdialog.py:725
msgid "on remote host"
msgstr ""

#: ../../qt4/settingsdialog.py:699
msgid "Run 'ionice':"
msgstr ""

#: ../../qt4/settingsdialog.py:708
msgid "when taking a manual snapshot"
msgstr ""

#: ../../qt4/settingsdialog.py:715
msgid "Run 'rsync' with 'nocache':"
msgstr ""

#: ../../qt4/settingsdialog.py:721
msgid "on local machine"
msgstr ""

#: ../../qt4/settingsdialog.py:731
msgid "Limit rsync bandwidth usage: "
msgstr "Az rsync sávszélesség-használatának korlátja: "

#: ../../qt4/settingsdialog.py:734
msgid " KB/sec"
msgstr " KB/sec"

#: ../../qt4/settingsdialog.py:769
msgid "Preserve ACL"
msgstr "ACL-ek megtartása"

#: ../../qt4/settingsdialog.py:782
msgid "Preserve extended attributes (xattr)"
msgstr "Kiterjesztett jogosultságok (xattr) megtartása"

#: ../../qt4/settingsdialog.py:800
msgid "Copy unsafe links (works only with absolute links)"
msgstr "Nem biztonságos linkek másolása (csak abszolút linkekkel működik)"

#: ../../qt4/settingsdialog.py:812
msgid "Copy links (dereference symbolic links)"
msgstr "Linkek másolása (szimbolikus linkeknél nem csak a hivatkozást)"

#: ../../qt4/settingsdialog.py:831
msgid "Paste additional options to rsync"
msgstr ""

#: ../../qt4/settingsdialog.py:834
msgid ""
"Options must be quoted e.g. --exclude-from=\"/path/to/my exclude file\"."
msgstr ""

#: ../../qt4/settingsdialog.py:848
msgid "Restore Config"
msgstr ""

#: ../../qt4/settingsdialog.py:863
msgid "New profile"
msgstr "Új profil"

#: ../../qt4/settingsdialog.py:879
msgid "Rename profile"
msgstr "Profil átnevezése"

#: ../../qt4/settingsdialog.py:893
#, python-format
msgid "Are you sure you want to delete the profile \"%s\" ?"
msgstr "Biztosan törlöd a(z) \"%s\" profilt?"

#: ../../qt4/settingsdialog.py:1132
msgid ""
"Custom Hours can only be a comma seperate list of hours (e.g. 8,12,18,23) or "
"*/3 for periodic backups every 3 hours"
msgstr ""
"Az egyedi órák csak vesszővel elválasztott, listázott értékek lehetnek (pl. "
"8,12,18,23), vagy */3, ha háromóránként akarsz mentést készíteni."

#: ../../qt4/settingsdialog.py:1474
msgid "Exclude pattern"
msgstr "Kihagyási minta"

#: ../../qt4/settingsdialog.py:1486
msgid "Exclude file"
msgstr "Kihagyandó fájl"

#: ../../qt4/settingsdialog.py:1490
msgid "Exclude folder"
msgstr "Kihagyandó mappa"

#: ../../qt4/settingsdialog.py:1509
msgid "Include file"
msgstr "Felveendő fájl"

#: ../../qt4/settingsdialog.py:1517 ../../qt4/settingsdialog.py:1537
#, python-format
msgid ""
"\"%s\" is a symlink. The linked target will not be backed up until you "
"include it, too.\n"
"Would you like to include the symlinks target instead?"
msgstr ""

#: ../../qt4/settingsdialog.py:1529
msgid "Include folder"
msgstr "Felveendő mappa"

#: ../../qt4/settingsdialog.py:1556
msgid "Are you sure you want to change snapshots folder ?"
msgstr "Biztos, hogy szeretnéd megváltoztatni a pillanatképek mappáját?"

#: ../../qt4/settingsdialog.py:1667
msgid "enabled"
msgstr ""

#: ../../qt4/settingsdialog.py:1669
msgid "disabled"
msgstr ""

#: ../../qt4/settingsdialog.py:1670
msgid "default"
msgstr ""

#: ../../qt4/settingsdialog.py:1694
msgid "Restore Settings"
msgstr ""

#: ../../qt4/settingsdialog.py:1711
msgid " and add your user to group 'fuse'"
msgstr ""

#: ../../qt4/settingsdialog.py:1715
#, python-format
msgid ""
"Please navigate to the snapshot from which you want to restore %(appName)s's "
"configuration. The path may look like: \n"
"%(samplePath)s\n"
"\n"
"If your snapshots are on a remote drive or if they are encrypted you need to "
"manually mount them first. If you use Mode SSH you also may need to set up "
"public key login to the remote host%(addFuse)s.\n"
"Take a look at 'man backintime'."
msgstr ""

#: ../../qt4/settingsdialog.py:1773 ../../qt4/settingsdialog.py:1835
msgid "No config found"
msgstr ""

#: ../../qt4/snapshotsdialog.py:48 ../../qt4/snapshotsdialog.py:171
msgid "Diff Options"
msgstr "Diff beállítások"

#: ../../qt4/snapshotsdialog.py:55
msgid "Command:"
msgstr "Parancs:"

#: ../../qt4/snapshotsdialog.py:59
msgid "Parameters:"
msgstr "Paraméterek:"

#: ../../qt4/snapshotsdialog.py:63
msgid "Use %1 and %2 for path parameters"
msgstr "Használja ezeket útvonal-paraméterként: %1 és %2"

#: ../../qt4/snapshotsdialog.py:105
msgid "List only different snapshots"
msgstr "Csak az eltérő pillanatképek listázása"

#: ../../qt4/snapshotsdialog.py:112
msgid "List only equal snapshots to: "
msgstr "Csak a következőkkel megegyező pillanatképek listázása: "

#: ../../qt4/snapshotsdialog.py:122
msgid "Deep check (more accurate, but slow)"
msgstr "Alapos ellenőrzés (pontosabb, de lassú)"

#: ../../qt4/snapshotsdialog.py:143
msgid "Delete"
msgstr "Töröl"

#: ../../qt4/snapshotsdialog.py:147
msgid "Select All"
msgstr "Minden kijelölése"

#: ../../qt4/snapshotsdialog.py:161
msgid "Diff"
msgstr "Különbség"

#: ../../qt4/snapshotsdialog.py:170
msgid "Go To"
msgstr "Ugrás ide:"

#: ../../qt4/snapshotsdialog.py:339
msgid "You can't compare a snapshot to itself"
msgstr "Egy pillanatkép nem hasonlítható össze önmagával"

#: ../../qt4/snapshotsdialog.py:346
#, python-format
msgid "Command not found: %s"
msgstr "A következő parancs nem található: %s"

#: ../../qt4/snapshotsdialog.py:367
#, python-format
msgid ""
"Do you really want to delete \"%(file)s\" in snapshot \"%(snapshot_id)s?\n"
msgstr ""
"Biztosan töröljem a \"%(file)s\" fájlt a \"%(snapshot_id)s pillanatképből?\n"

#: ../../qt4/snapshotsdialog.py:370
#, python-format
msgid "Do you really want to delete \"%(file)s\" in %(count)d snapshots?\n"
msgstr "Biztos, hogy törlöd a \"%(file)s\"-t a \"%(count)d-pillanatképből?\n"

#: ../../qt4/snapshotsdialog.py:372
msgid "WARNING: This can not be revoked!"
msgstr "Nem lehet visszavonni!"

#: ../../qt4/snapshotsdialog.py:385
#, python-format
msgid "Exclude \"%s\" from future snapshots?"
msgstr "Kizárjam a \"%s\"-t a jövőbeli pillanatképekből?"
